  - name: Run a test nginx container
    community.docker.docker_container:
      name: test-nginx
      image: nginx:latest
      state: started
      published_ports:
        - "8080:80"

      
    - name: Ensure the test file exists
      file:
        path: /tmp/test_file.txt
        state: touch
        mode: '0644'
- hosts: localhost
  gather_facts: true
  ignore_unreachable: true
  vars_files:
    - vars/default.yml
  tasks:
    - name: Install Apache packages
      become: true
      ansible.builtin.yum:
        name: httpd
        state: present
        use_backend: yum
    - name: Debug Message - Tagged with 'test'
      ansible.builtin.debug:
        msg: "This task should run when the 'test' tag is targeted"
      tags:
      - test

    - name: Ensure the test file exists
      file:
        path: /tmp/test_file.txt
        state: touch
        mode: '0644'

    - name: Create document root
      become: true
      ansible.builtin.file:
        state: directory
        dest: "{{ doc_root }}"
        mode: 0701

    - name: Create configuration file
      become: true
      ansible.builtin.template:
        src: spacelift.conf.j2
        dest: /etc/httpd/conf.d/spacelift.conf
        mode: 0644
      notify: Restart server

    - name: Copy web pages
      become: true
      ansible.builtin.template:
        src: index.html.j2
        dest: "{{ doc_root }}/index.html"
      tags:
        - content

    - name: Ensure httpd is running
      become: true
      ansible.builtin.service:
        name: httpd
        state: started
      ignore_errors: "{{ ansible_check_mode }}"

  handlers:
    - name: Restart server
      become: true
      ansible.builtin.service:
        name: httpd
        state: restarted
      ignore_errors: "{{ ansible_check_mode }}"
