- name: Test file creation for config management
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create a file with versioned content
      ansible.builtin.copy:
        dest: /tmp/test_cm_file.txt
        content: "Version 2"
        mode: '0644'
      tags:
        - test
